update

diff --git a/archbase b/archbase
--- a/archbase
+++ b/archbase
@@ -2,30 +2,30 @@
 
 setfont ter-132b
 
-error() {
-    echo "${1}"
-    exit 1
-}
-
 verify_system() {
-    if [[ -f /usr/bin/pacstrap ]]; then
-        error "Not in arch live env"
+    if [[ ! -f /usr/bin/pacstrap ]]; then
+        echo "Not in arch live env"
+        exit 1
     fi
 
     if [[ "$(id -u)" != "0" ]]; then
-        error "Not running as root"
+        echo "Not running as root"
+        exit 1
     fi
 
     if [[ "$(cat /sys/firmware/efi/fw_platform_size)" != "64" ]]; then
-        error "Not booted in a supported mode (x64 UEFI)"
+        echo "Not booted in a supported mode (x64 UEFI)"
+        exit 1
     fi
 
     if ! ping -qn -c 1 ping.archlinux.org &>/dev/null; then
-        error "Not internet connection"
+        echo "No internet connection"
+        exit 1
     fi
 
     if [[ "$(timedatectl show -p NTPSynchronized --value)" != "yes" ]]; then
-        error "System clock is not synchronized"
+        echo "System clock is not synchronized"
+        exit 1
     fi
 }
 
@@ -102,7 +102,8 @@ get_user_input() {
         fi
 
         if [[ ! -b "${_disk}" ]]; then
-            error "Drive '${_disk}' is not valid"
+            echo "Drive '${_disk}' is not valid"
+            exit 1
         fi
 
         if [[ "${_disk}" =~ "nvme" ]]; then
@@ -115,7 +116,8 @@ get_user_input() {
         if [[ "${REPLY:-N}" =~ [yY] ]]; then
             break
         else
-            error "Aborted by user"
+            echo "Aborted by user"
+            exit 0
         fi
     done
 
@@ -142,6 +144,7 @@ prepare_disk() {
     mkfs.ext4 "${root_partition}"
     mount "${root_partition}" /mnt
     mount --mkdir "${boot_partition}" /mnt/boot
+}
 
 install_arch() {
     pacman -Sy --noconfirm archlinux-keyring
@@ -176,6 +179,8 @@ install_arch() {
         nano
         networkmanager
         sudo
+        zram-generator
+        zstd
     )
     
     pacstrap -K /mnt "${pacstrap_pkgs[@]}"
@@ -215,6 +220,14 @@ configure_arch() {
 		sed -i 's/^# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers
 		sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers
         rm -rf /etc/skel/archsetup
+
+        # zram config file
+        cat <<- Z_EOF > /etc/systemd/zram-generator.conf
+            [zram0]
+            zram-size = min(ram / 2, 4096)
+            compression-algorithm = zstd
+        Z_EOF
+
 		exit
 	EOF
 }
diff --git a/archsetup/archsetup b/archsetup/archsetup
--- a/archsetup/archsetup
+++ b/archsetup/archsetup
@@ -1,26 +1,35 @@
 #!/bin/bash
 
-error() { echo "[ERROR] ${1}"; exit 1; }
-warning() { echo "[WARNING] ${1}"; }
-
 install_yay() {
-    git clone https://aur.archlinux.org/yay /tmp/yay || { warning "Failed to clone 'yay' repository"; return 1; }
-    (cd /tmp/yay && makepkg -si --noconfirm) || { warning "Failed to build and install 'yay'"; return 1; }
-    return 0
+    if ! git clone https://aur.archlinux.org/yay /tmp/yay; then
+        echo "Failed to clone 'yay' repository"
+        return 1
+    elif ! (cd /tmp/yay && makepkg -si --noconfirm); then
+        echo "Failed 'makepkg' for 'yay'"
+        return 1
+    else
+        return 0
+    fi
 }
 
-sudo pacman -Sy || error "Failed to synchronize package databases"
+sudo pacman -Sy
 
 if [[ -f pacman.pkgs ]]; then
-    sudo pacman -S --noconfirm --needed - < pacman.pkgs || error "Failed to install packages from 'pacman.pkgs'"
+    sudo pacman -S --noconfirm --needed - < pacman.pkgs
 else
-    warning "No 'pacman.pkgs' file found. Skipping 'pacman' package installation."
+    echo "No 'pacman.pkgs' file found. Skipping 'pacman' package installation."
 fi  
 
-if ! command -v yay; then
-    if install_yay; then
-        [[ -f yay.pkgs ]] && yay -S --noconfirm --needed - < yay.pkgs || warning "Failed to install packages from 'yay.pkgs'"
-    else
-        warning "Continuing without 'yay' packages"
+if command -v yay 1>/dev/null; then
+    echo "Already installed: 'yay'"
+else
+    if ! install_yay; then
+        echo "Failed to install: 'yay'"
     fi
+fi
+
+if [[ -f yay.pkgs ]]; then
+    yay -S --noconfirm --needed - < yay.pkgs
+else
+    echo "No 'yay.pkgs' file found. Skipping 'yay' package installation."
 fi
